sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
- '13'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: QoFqgglU28GOkBtim/h/VMHfEpnxTVX/KuIDsu462cV3LjhibrcpCJvFUR7UqNQZ+FfovJWr+AyN/ZLFjYzENgXk5opUA8N++3oqZoPkKInZanTaDUq/u/yDbauSaj9IuFlmo9LgbK9/papEyLIskTz2WqpQ3sjIM7nw32AAgHdwIVTqgCv/4+cvdvzXu8AzCKzZxbNhkV2daZfWJ/sbZ4SoCSYigcoL1cFR/PbVKVoebgUGSyWXBlERI6vdarML8kzOOeaArQ5M+UFW7HoTrsJsEhlnCIpYYBZb2rCtgGTbW1uR7H3wN5P1hINqOwAKtGf92OxqYBlb38ojw4ofoicAdLf5sAp+0tFUre2IBo8EfjQdj44O7ZVy778+gFgeLcBdfTj9yJJcRb9OiIJoGBmRMCx7OwJawzP72lwbFyOIu5eWtih7IlRNrIbyVP2eykFb1worjhK0jt8xOyhBtWyaz3zVvBWw8cpcD9SECR+g1zisM09l745xIsrpAsYze9Y3NcgttfZYO6+0FZ+81T5loz40LAfBaAIvLmViiouZEaYom3EUplVm5427xBmcXez/X1EHnNLEciG/5NBi5RQXKvdOHdlzG3CAxOsc+BAnwJrfi8J5jo/Li2QIrqh38YeJRUYYTReFxMHfdyDC72qY6g5KpEYo+KO/+W9kT/g=
